#  _____ ______  _____   _     _           _ _   
# /  __ \| ___ \/  ___| | |   (_)         (_) |  
# | /  \/| |_/ /\ `--.  | |    _ _ __ ___  _| |_ 
# | |    |  __/  `--. \ | |   | | '_ ` _ \| | __|
# | \__/\| |    /\__/ / | |___| | | | | | | | |_ 
#  \____/\_|    \____/  \_____/_|_| |_| |_|_|\__|
# -----------------------------------------
#   Configuration File for CPS Limit
# -----------------------------------------


#   / ___|  _ \/ ___|
#  | |   | |_) \___ \
#  | |___|  __/ ___) |
#   \____|_|   |____/
# The maximum allowed clicks per second.
# Any click above this rate (within a sliding 1s + ping window) will be cancelled.
# Default: 20
cps-threshold:
  left: 18
  right: 20
# Fallback CPS Threshold
cps-threshold-default: 20
# When a player actually lands a hit while over the CPS threshold,
# further hits are cancelled for this many seconds.
# Default: 1.0
hit-miss-cooldown-seconds: 1.0


#  |  _ \ _ __ ___  / _(_) | ___ 
#  | |_) | '__/ _ \| |_| | |/ _ \
#  |  __/| | | (_) |  _| | |  __/
#  |_|   |_|  \___/|_| |_|_|\___|                             
# profiles section (all keys optional; any missing falls back to defaults above)
profiles:
  vip:
    permission: cpslimiter.profile.vip
    cps-threshold:
      left: 20
      right: 20
    hit-miss-cooldown-seconds: 0.5