name: CPSLimiter
version: 1.0-SNAPSHOT
main: dev.ikara.cpslimiter.CpsLimit
description: CPS limiter with live debug alerts and bypass permission
authors:
  - oipika

commands:
  cpsdebug:
    description: Toggle live CPS debug alerts
    usage: /cpsdebug
    permission: cpslimiter.debug

permissions:
  cpslimiter.debug:
    description: Allows toggling CPS debug alerts
    default: op

  cpslimiter.bypass:
    description: Completely bypass CPS limits, cooldowns, and cancellations
    default: op